# Generated by Django 4.1.1 on 2022-09-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30)),
                ('shoplocation', models.CharField(max_length=30)),
                ('shopcontactno', models.IntegerField()),
                ('shop_image', models.ImageField(default='null.jpg', upload_to='Image')),
            ],
        ),
    ]
