# Generated by Django 4.1.1 on 2022-09-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Accountsdb',
        ),
    ]
